// Code generated by "stringer -type=DocMDPPerm"; DO NOT EDIT.

package sign

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DoNotAllowAnyChangesPerms-1]
	_ = x[AllowFillingExistingFormFieldsAndSignaturesPerms-2]
	_ = x[AllowFillingExistingFormFieldsAndSignaturesAndCRUDAnnotationsPerms-3]
}

const _DocMDPPerm_name = "DoNotAllowAnyChangesPermsAllowFillingExistingFormFieldsAndSignaturesPermsAllowFillingExistingFormFieldsAndSignaturesAndCRUDAnnotationsPerms"

var _DocMDPPerm_index = [...]uint8{0, 25, 73, 139}

func (i DocMDPPerm) String() string {
	i -= 1
	if i >= DocMDPPerm(len(_DocMDPPerm_index)-1) {
		return "DocMDPPerm(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DocMDPPerm_name[_DocMDPPerm_index[i]:_DocMDPPerm_index[i+1]]
}
